#!/bin/sh

cmake --build build --target clean

rm -fv *.o
rm -fv hello

rm -fv *.exe

rm -rfv __voidcache__
rm -rfv library/import/llvm-c/__voidcache__
rm -rfv library/import/llvm-c/*/__voidcache__
rm -rfv compiler/import/level-??/__voidcache__

