#!/bin/sh

rm -rfv build

rm -fv *.o
rm -fv hello

rm -fv *.exe

rm -rfv __voidcache__
rm -rfv compiler/import/__voidcache__
rm -rfv compiler/import/level-??/__voidcache__
rm -rfv compiler/test/level-??/__voidcache__
rm -rfv library/import/__voidcache__
rm -rfv library/import/*/__voidcache__
rm -rfv library/import/llvm-c/*/__voidcache__

